# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'unsplash_with_storyboard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for unsplash_with_storyboard
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Alamofire', '~> 5.5'  
end
